# -*- coding: utf-8 -*-

from cvlayer.cv.window import (
    WINDOW_AUTOSIZE,
    WINDOW_FREERATIO,
    WINDOW_FULLSCREEN,
    WINDOW_GUI_EXPANDED,
    WINDOW_GUI_NORMAL,
    WINDOW_KEEPRATIO,
    WINDOW_NORMAL,
    WINDOW_OPENGL,
    Window,
)


class CvlWindow:
    WINDOW_AUTOSIZE_VALUE = WINDOW_AUTOSIZE
    WINDOW_FREERATIO_VALUE = WINDOW_FREERATIO
    WINDOW_FULLSCREEN_VALUE = WINDOW_FULLSCREEN
    WINDOW_GUI_EXPANDED_VALUE = WINDOW_GUI_EXPANDED
    WINDOW_GUI_NORMAL_VALUE = WINDOW_GUI_NORMAL
    WINDOW_KEEPRATIO_VALUE = WINDOW_KEEPRATIO
    WINDOW_NORMAL_VALUE = WINDOW_NORMAL
    WINDOW_OPENGL_VALUE = WINDOW_OPENGL

    @staticmethod
    def cvl_create_window(name: str, flags=WINDOW_AUTOSIZE) -> Window:
        return Window(name, flags)
